export const colors = {
  backgroundDark: "#0b0f14",
  backgroundSecondary: "#161a21",
  textLight: "#e6edf3",
  textMuted: "#9ca3af",
  textPlaceholder: "#9e9e9e",
  textLink: "#6ca0ff",
  textFooter: "#a3b1c2",
  borderGray: "#3a3f44",
  borderFocus: "#0096ff",
  buttonPrimary: "#0096ff",
  buttonGoogleBg: "#1a1f27",
  buttonGoogleText: "#fff",
};

export const spacing = {
  paddingMain: "2rem 1rem",
  paddingMainMd: "2rem 4rem",
  paddingMainLg: "4rem 10.8rem",
  paddingContent: "3rem",
  paddingContentMd: "1.5rem",
  paddingContentSm: "1rem",
  paddingInput: "0.8rem 1rem",
  paddingButton: "0.9rem",
  paddingGoogle: "0.9rem 1.2rem",
  gapField: "0.7rem",
  gapForm: "1rem",
  gapDivider: "1rem",
  gapIcon: "0.7rem",
  gapGoogle: "12px",
  marginBottomBrand: "2rem",
  marginBottomHeading: "0.5rem",
  marginTopForm: "2rem",
  marginTopRow: "0.5rem",
  marginTopDivider: "1.1rem",
  marginTopFooter: "1rem",
};
